### ISSUE TITLE
all users are considered active

### ISSUE THREAD

**Issue by iamtalhaasghar** [marcus67/little_brother#194]
Suppose person A powered on PC and starts using it. Person B is also considered active during this time. So, if we have 2 hr play time for each user and person A plays for 2 hrs then person B can not use system anymore.

**Comment by marcus67** [comment]
Hi @iamtalhaasghar, this is perfectly true. It's one of the drawbacks when using the PING feature of Little Brother and the target host is used by several users. This can only be fixed by installing the LittleBrother client and that's currently only possible if it's a Linux host. 

I know that at least one of the LittleBrother users is considering writing a client for Windows which would close this gap. I do not know, however, how far he has proceeded.

**Comment by iamtalhaasghar** [comment]
if someone is having same problem then you can also look into an alternative FOSS solution https://mjasnik.gitlab.io/timekpr-next/
